random seed: 1
num class labels: 3
learning rate: 0.001
batch size: 32
hidden layer size: 32
num epochs: 1000
num workers: 0
validation fraction: 0.1
drop_prob: 0.2


data path: '/Users/libinvarghese/Documents/Jesna/Git_ML/ML_algorithms_Scratch/data/Iris.csv'
features : ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
target : Species

map : {'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}